import type { ReactNode } from 'react';

// ============================================
// Core Types
// ============================================

/**
 * Source string collected from production
 */
export interface SourceString {
	/** Original text in source language */
	text: string;
	/** Hash for lookup */
	hash: string;
	/** Optional context for disambiguation */
	context?: string | null;
	/** Number of times this string was seen */
	occurrences?: number;
	/** Last time this string was encountered */
	lastSeenAt?: Date;
}

/**
 * Translation entry
 */
export interface Translation {
	hash: string;
	text: string;
	locale: string;
	autoGenerated?: boolean;
	reviewed?: boolean;
}

/**
 * Locale information
 */
export interface LocaleInfo {
	code: string;
	name: string;
	nativeName: string;
}

// ============================================
// Adapter Interfaces
// ============================================

/**
 * Storage adapter for translations
 * Implement this interface for different storage backends (DB, file, API, etc.)
 */
export interface StorageAdapter {
	/**
	 * Get all translations for a locale
	 * @returns Map of hash -> translated text
	 */
	getTranslations(locale: string): Promise<Map<string, string>>;

	/**
	 * Register source strings (batch insert, skip duplicates)
	 */
	registerSources(
		sources: Array<{
			text: string;
			hash: string;
			context?: string;
		}>
	): Promise<void>;

	/**
	 * Save a single translation
	 */
	saveTranslation(
		locale: string,
		hash: string,
		text: string,
		options?: {
			sourceText?: string;
			context?: string;
			autoGenerated?: boolean;
		}
	): Promise<void>;

	/**
	 * Save multiple translations at once
	 */
	saveTranslations?(
		locale: string,
		translations: Array<{ hash: string; text: string; sourceText?: string }>
	): Promise<void>;

	/**
	 * Get all source strings
	 */
	getSources(): Promise<SourceString[]>;

	/**
	 * Get untranslated strings for a locale
	 */
	getUntranslated(locale: string): Promise<SourceString[]>;

	/**
	 * Delete a translation
	 */
	deleteTranslation?(locale: string, hash: string): Promise<void>;
}

/**
 * Translation adapter for auto-generating translations
 * Implement this interface for different translation services (LLM, API, etc.)
 */
export interface TranslateAdapter {
	/**
	 * Translate a single text
	 */
	translate(
		text: string,
		options: {
			from: string;
			to: string;
			context?: string;
		}
	): Promise<string>;

	/**
	 * Translate multiple texts at once (optional, for efficiency)
	 */
	translateBatch?(
		texts: Array<{ text: string; context?: string }>,
		options: {
			from: string;
			to: string;
		}
	): Promise<string[]>;
}

// ============================================
// Context Types
// ============================================

/**
 * I18n context stored in AsyncLocalStorage
 */
export interface I18nContext {
	locale: string;
	defaultLocale: string;
	/** hash -> translated text (for server lookup) */
	translations: Map<string, string>;
	/** source -> translated text (for client) */
	translationsForClient: Record<string, string>;
	/** Storage adapter for flushing collected strings */
	storage?: StorageAdapter;
}

/**
 * Translation options
 */
export interface TranslateOptions {
	/** Context for disambiguation (e.g., "button", "menu") */
	context?: string;
}

// ============================================
// Client Types
// ============================================

/**
 * Translation context value for React
 */
export interface TranslationContextValue {
	locale: string;
	t: (text: string, params?: Record<string, string | number>) => string;
}

/**
 * Props for I18nProvider
 */
export interface I18nProviderProps {
	children: ReactNode;
	/** Current locale code */
	locale: string;
	/** Translations map (source text -> translated text) */
	translations: Record<string, string>;
}
